defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 20
  #http://dev.mysql.com/doc/refman/5.0/en/auto-reconnect.html
  reconnect: false
  host: 127.0.0.1
  username: root
  password: ""

development: &DEV
  <<: *defaults
  database: spendon_dev

test: &TEST
  <<: *defaults
  database: spendon_test

production: &PRD
  <<: *defaults
  database: spendon_dev
